-- MySQL Script generated by MySQL Workbench
-- Wed 25 May 2016 07:06:59 PM WAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weather_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather_station` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `weather_station` ;

-- -----------------------------------------------------
-- Table `weather_station`.`stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`stations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `location` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `date_of_creation` TEXT NOT NULL COMMENT '',
  `last_received` TEXT NULL DEFAULT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `weather_station`.`weather_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`weather_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `station_id` INT(11) NOT NULL COMMENT '',
  `temperature` DECIMAL(10,0) NOT NULL COMMENT '',
  `humidity` DECIMAL(10,0) NOT NULL COMMENT '',
  `heat_index` DECIMAL(10,0) NOT NULL COMMENT '',
  `amt_of_rain` DECIMAL(10,0) NOT NULL COMMENT '',
  `wind_speed` DECIMAL(10,0) NOT NULL COMMENT '',
  `wind_direction` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `datetime` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `id` (`station_id` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  CONSTRAINT `weather_data_ibfk_1`
    FOREIGN KEY (`station_id`)
    REFERENCES `weather_station`.`stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
